### ISSUE TITLE
IBKR shortened decimal bug

### ISSUE THREAD

**Issue by SamyCoenen** [samjmck/tobcalc#1]
When the amount has a decimal such as .10, .20, .50 it gets exported to a CSV by IBKR as "100.1", "100.2", "100.5" which gets converted into a tax base of 10.01, 10.02, 10.05.
https://github.com/samjmck/tobcalc/blob/1de3c9e53f378e573a54b78dff6e5fcc4f313fe8/src/adapters/IBKR_adapter.ts#L70

**Comment by samjmck** [comment]
Thanks for opening this, this has been fixed in 9c35749eb6ddcc611dee4891197d015e7ae32222.
